package stirling.software.jpdfium.crop;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.contentstream.PDFStreamEngine;
import org.apache.pdfbox.contentstream.operator.Operator;
import org.apache.pdfbox.cos.COSBase;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDResources;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.TextPosition;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import stirling.software.jpdfium.PdfDocument;
import stirling.software.jpdfium.PdfPage;
import stirling.software.jpdfium.model.Rect;
import stirling.software.jpdfium.transform.PdfPageGeometry;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Cross-library ground-truth verification for the crop-remove-content path.
 *
 * <p>The input PDFs are generated by {@link CropTestPdfGenerator} at known coordinates
 * (the layout is the specification). The crop is applied through JPDFium and the output
 * is then re-opened with <b>PDFBox</b> - an independent parser - so the assertions never
 * round-trip through the same native library that produced the file.
 *
 * <p>Run: {@code ./gradlew :jpdfium:integrationTest --tests "stirling.software.jpdfium.crop.*"}
 */
@EnabledIfSystemProperty(named = "jpdfium.integration", matches = "true")
class CropPdfBoxVerificationTest {

    private static final Rect LEFT_HALF = new Rect(0, 0, 306, 792);

    // text grid

    @Test
    void textOutsideLeftHalfCropIsGoneAndInsideSurvivesAtSamePlace() throws Exception {
        byte[] input = CropTestPdfGenerator.textGridPdf();
        byte[] output = cropFirstPage(input, LEFT_HALF);

        try (PDDocument doc = Loader.loadPDF(output)) {
            assertEquals(1, doc.getNumberOfPages(), "page count changed");

            PDPage page = doc.getPage(0);
            assertRectEquals(new PDRectangle(LEFT_HALF.x(), LEFT_HALF.y(),
                            LEFT_HALF.x() + LEFT_HALF.width(), LEFT_HALF.y() + LEFT_HALF.height()),
                    page.getMediaBox(), "MediaBox must equal the crop rect");
            assertRectEquals(page.getMediaBox(), page.getCropBox(), "CropBox must equal MediaBox");

            // Independent text extraction via PDFBox (not PDFium).
            List<Glyph> glyphs = extractGlyphs(doc);

            // Kept words must exist at their original position.
            assertGlyph(glyphs, "KEEP_A", 100, 700, page);
            assertGlyph(glyphs, "KEEP_B", 200, 700, page);
            assertGlyph(glyphs, "KEEP_C", 100, 600, page);
            assertGlyph(glyphs, "KEEP_D", 200, 600, page);

            // Dropped words must be physically gone from the content stream.
            assertNoWord(glyphs, "DROP_A");
            assertNoWord(glyphs, "DROP_B");
            assertNoWord(glyphs, "DROP_C");
            assertNoWord(glyphs, "DROP_D");
        }
    }

    // images

    @Test
    void imageOutsideCropIsNotDrawnInsideAndStraddlingImagesSurvive() throws Exception {
        byte[] input = CropTestPdfGenerator.imagePdf();
        byte[] output = cropFirstPage(input, LEFT_HALF);

        try (PDDocument doc = Loader.loadPDF(output)) {
            assertEquals(1, doc.getNumberOfPages());
            PDPage page = doc.getPage(0);
            PDResources res = page.getResources();

            // Map each surviving image XObject to its dominant colour so we can tell them apart.
            String insideName = null, outsideName = null, straddleName = null;
            for (COSName name : res.getXObjectNames()) {
                PDImageXObject img = (PDImageXObject) res.getXObject(name);
                int color = dominantColor(img.getImage());
                if (color == 0xFF0000) insideName = name.getName();
                else if (color == 0x0000FF) outsideName = name.getName();
                else if (color == 0x00FF00) straddleName = name.getName();
            }
            // Contract: the fully-outside image must not be drawn; it may also be fully
            // dropped from the page Resources (PDFium resource GC) - both are acceptable.
            assertTrue(insideName != null, "fully-inside image must survive");
            assertTrue(straddleName != null, "straddling image must survive");

            Set<String> drawn = drawnXObjectNames(page);
            assertTrue(drawn.contains(insideName), "fully-inside image must still be drawn");
            assertTrue(drawn.contains(straddleName), "straddling image must still be drawn");
            assertFalse(outsideName != null && drawn.contains(outsideName),
                    "fully-outside image must not be drawn after crop");
        }
    }

    // form XObjects

    @Test
    void formEmbeddedTextOutsideCropIsRemoved() throws Exception {
        byte[] input = CropTestPdfGenerator.formTextPdf();
        byte[] output = cropFirstPage(input, LEFT_HALF);

        try (PDDocument doc = Loader.loadPDF(output)) {
            List<Glyph> glyphs = extractGlyphs(doc);
            assertGlyph(glyphs, "FORM_IN", 100, 700, doc.getPage(0));
            assertNoWord(glyphs, "FORM_OUT");
        }
    }

    // boxes

    @Test
    void pageBoxesAreSetToTheCropRect() throws Exception {
        byte[] output = cropFirstPage(CropTestPdfGenerator.plainLetterPdf(),
                new Rect(72, 72, 468, 648));
        try (PDDocument doc = Loader.loadPDF(output)) {
            PDPage page = doc.getPage(0);
            // Crop Rect(72,72,468,648) -> box [72,72,540,720].
            PDRectangle expected = new PDRectangle(72, 72, 468, 648);
            assertRectEquals(expected, page.getMediaBox(), "MediaBox");
            assertRectEquals(expected, page.getCropBox(), "CropBox");
            assertRectEquals(expected, page.getTrimBox(), "TrimBox");
            assertRectEquals(expected, page.getBleedBox(), "BleedBox");
            assertRectEquals(expected, page.getArtBox(), "ArtBox");
        }
    }

    // never break

    @Test
    void outputStillRendersThroughPdfium() throws Exception {
        byte[] output = cropFirstPage(CropTestPdfGenerator.textGridPdf(), LEFT_HALF);
        try (PdfDocument doc = PdfDocument.open(output); PdfPage page = doc.page(0)) {
            int area = page.renderAt(72).width() * page.renderAt(72).height();
            assertTrue(area > 0, "output must render");
        }
    }

    // helpers

    private static byte[] cropFirstPage(byte[] input, Rect crop) {
        try (PdfDocument doc = PdfDocument.open(input)) {
            PdfPageGeometry.cropAndRemoveContent(doc, 0, crop);
            return doc.saveBytes();
        }
    }

    /** Extract text runs + baseline origin (PDFBox y measured from page top) via PDFBox. */
    private static List<Glyph> extractGlyphs(PDDocument doc) throws IOException {
        GlyphStripper stripper = new GlyphStripper();
        stripper.getText(doc);
        return stripper.glyphs();
    }

    /** PDFTextStripper subclass that records each text run and its first glyph position. */
    private static final class GlyphStripper extends PDFTextStripper {
        private final List<Glyph> glyphs = new ArrayList<>();
        GlyphStripper() throws IOException { /* super() throws IOException */ }
        List<Glyph> glyphs() { return glyphs; }
        @Override
        protected void writeString(String text, List<TextPosition> textPositions) {
            if (textPositions == null || textPositions.isEmpty() || text == null) return;
            TextPosition tp = textPositions.get(0);
            glyphs.add(new Glyph(text, tp.getXDirAdj(), tp.getYDirAdj()));
        }
    }

    private static void assertGlyph(List<Glyph> glyphs, String word, double pdfX, double pdfY,
                                    PDPage page) {
        // PDFBox reports y measured from the TOP of the page.
        double expectedX = pdfX;
        double expectedY = page.getMediaBox().getHeight() - pdfY;
        for (Glyph g : glyphs) {
            if (g.text().trim().equals(word)
                    && Math.abs(g.x() - expectedX) < 3.0
                    && Math.abs(g.y() - expectedY) < 3.0) {
                return;
            }
        }
        throw new AssertionError("expected word '" + word + "' at (" + pdfX + "," + pdfY
                + ") PDF points; glyphs=" + glyphs);
    }

    private static void assertNoWord(List<Glyph> glyphs, String word) {
        for (Glyph g : glyphs) {
            assertFalse(g.text().trim().equals(word),
                    "word '" + word + "' must be gone but found at x=" + g.x() + " y=" + g.y());
        }
    }

    /** Parse the page content stream and return every XObject name referenced by a Do operator. */
    private static Set<String> drawnXObjectNames(PDPage page) throws IOException {
        Set<String> names = new HashSet<>();
        PDFStreamEngine engine = new PDFStreamEngine() {
            @Override
            protected void processOperator(Operator operator, List<COSBase> operands) {
                if ("Do".equals(operator.getName()) && !operands.isEmpty()) {
                    COSName name = (COSName) operands.get(0);
                    names.add(name.getName());
                }
            }
        };
        engine.processPage(page);
        return names;
    }

    private static void assertRectEquals(PDRectangle expected, PDRectangle actual, String ctx) {
        String e = String.format("[%.1f,%.1f,%.1f,%.1f]", expected.getLowerLeftX(),
                expected.getLowerLeftY(), expected.getUpperRightX(), expected.getUpperRightY());
        String a = String.format("[%.1f,%.1f,%.1f,%.1f]", actual.getLowerLeftX(),
                actual.getLowerLeftY(), actual.getUpperRightX(), actual.getUpperRightY());
        assertEquals(e, a, ctx);
    }

    private static int dominantColor(BufferedImage img) {
        return img.getRGB(img.getWidth() / 2, img.getHeight() / 2) & 0xFFFFFF;
    }

    record Glyph(String text, double x, double y) {}
}
