# GraalVM Reachability Metadata 1.0.10 entry for com.stirling:jpdfium
Args = -H:IncludeResources=natives/.* -H:IncludeResources=META-INF/native-image/com.stirling/jpdfium/.* --enable-native-access=ALL-UNNAMED
